apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nodejs
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nodejs
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/nodejs.git
